### ISSUE TITLE
Error compiling on fedora23-cloud-base

### ISSUE THREAD

**Issue by FireDrunk** [storaged-project/storaged#78]
To try devving for storaged, i've setup a vagrant box with the fedora/24-cloud-base image.
I've installed the build reqs with the dnf command found in the readme.

The configure command runs fine, but when i execute make i get the following output:

```
[root@localhost vagrant]# make
make  all-recursive
make[1]: Entering directory '/root/src/vagrant'
Making all in data
make[2]: Entering directory '/root/src/vagrant/data'
cp org.freedesktop.UDisks2.conf.in org.freedesktop.UDisks2.conf
  ITMRG  org.freedesktop.UDisks2.policy
make[2]: Leaving directory '/root/src/vagrant/data'
Making all in udisks
make[2]: Entering directory '/root/src/vagrant/udisks'
( top_builddir=`cd .. && pwd`; 						\
 cd . && glib-mkenums --template udisksenumtypes.h.template udisksenums.h ) | 	\
   sed 's,U_TYPE_DISKS,UDISKS_TYPE,' | sed 's,u_disks,udisks,' > 			\
   udisksenumtypes.h.tmp && mv udisksenumtypes.h.tmp udisksenumtypes.h
( top_builddir=`cd .. && pwd`; 						\
 cd . && glib-mkenums --template udisksenumtypes.c.template udisksenums.h ) | 	\
   sed 's,U_TYPE_DISKS,UDISKS_TYPE,' | sed 's,u_disks,udisks,' > 			\
   udisksenumtypes.c.tmp && mv udisksenumtypes.c.tmp udisksenumtypes.c
gdbus-codegen							                \
	--interface-prefix org.freedesktop.UDisks2.                          	\
	--c-namespace UDisks							\
	--c-generate-object-manager						\
	--generate-c-code udisks-generated                             		\
	--generate-docbook udisks-generated-doc					\
	../data/org.freedesktop.UDisks2.xml         			\
	
sed -e 's/@MAJOR_VERSION@/2/' -e 's/@MINOR_VERSION@/6/' -e 's/@MICRO_VERSION@/3/' ../udisks/udisksversion.h.in > udisksversion.h.tmp && mv udisksversion.h.tmp udisksversion.h
make  all-recursive
make[3]: Entering directory '/root/src/vagrant/udisks'
Making all in modules.conf.d
make[4]: Entering directory '/root/src/vagrant/udisks/modules.conf.d'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/root/src/vagrant/udisks/modules.conf.d'
make[4]: Entering directory '/root/src/vagrant/udisks'
  CC       libudisks2_la-udisksenumtypes.lo
  CC       libudisks2_la-udisks-generated.lo
  CC       libudisks2_la-udisksclient.lo
  CC       libudisks2_la-udisksobjectinfo.lo
  CC       libudisks2_la-udiskserror.lo
  CCLD     libudisks2.la
  GISCAN   UDisks-2.0.gir
gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
Traceback (most recent call last):
  File "/usr/bin/g-ir-scanner", line 66, in <module>
    sys.exit(scanner_main(sys.argv))
  File "/usr/lib64/gobject-introspection/giscanner/scannermain.py", line 544, in scanner_main
    shlibs = create_binary(transformer, options, args)
  File "/usr/lib64/gobject-introspection/giscanner/scannermain.py", line 419, in create_binary
    gdump_parser.get_error_quark_functions())
  File "/usr/lib64/gobject-introspection/giscanner/dumper.py", line 328, in compile_introspection_binary
    return dc.run()
  File "/usr/lib64/gobject-introspection/giscanner/dumper.py", line 167, in run
    introspection_obj = self._compile(c_path)
  File "/usr/lib64/gobject-introspection/giscanner/dumper.py", line 207, in _compile
    self._options.init_sections)
  File "/usr/lib64/gobject-introspection/giscanner/ccompiler.py", line 241, in compile
    source_str.rfind(os.sep)]))
  File "/usr/lib64/python2.7/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib64/python2.7/distutils/unixccompiler.py", line 134, in _compile
    raise CompileError, msg
distutils.errors.CompileError: command 'gcc' failed with exit status 1
/usr/share/gobject-introspection-1.0/Makefile.introspection:155: recipe for target 'UDisks-2.0.gir' failed
make[4]: *** [UDisks-2.0.gir] Error 1
make[4]: Leaving directory '/root/src/vagrant/udisks'
Makefile:853: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/root/src/vagrant/udisks'
Makefile:591: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/root/src/vagrant/udisks'
Makefile:512: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/src/vagrant'
Makefile:444: recipe for target 'all' failed
make: *** [all] Error 2
```

Note the: **gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory**

I don't know whether this is related to the image i'm using, or the configure scripting.
Can someone help me out with this?

**Comment by FireDrunk** [comment]
dnf install redhat-rpm-config

fixed the issue, so this should probably be included in the builddeps.
